django_scaffold/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django_scaffold.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', include('main.urls')),
    path('web_hook/', include('web_hook.urls')),
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls')),
    # path('silk/', include('silk.urls', namespace='silk')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', index, name='home'),
]

panel/modules/user_to_excel/urls.py
from django.urls import path

from panel.modules.user_to_excel.views import download_poll_pack_stats

user_to_excel_urlpatterns = [
    path('poll_packs_stats/', download_poll_pack_stats, name='stats_poll_packs'),
]

panel/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth import views as auth_views
from main.views import PanelLoginView
from panel.modules import load_modules_panel_url
from panel.views import *


app_name = 'panel'

urlpatterns = [
    path('', sender, name='sender'),
    path('broadcast', broadcast, name='broadcast'),
    path('status', status, name='status'),
    path('create', ProjectFormView.as_view(),  name='create'),
    path('project_list', ShowProject.as_view(), name='project_list'),
    path('users', login_required(UsersModeratorView.as_view()), name='users'),
    path('user_history/<int:pk>/', login_required(user_history), name='user_history'),
    path('search_by_users', login_required(search_by_users), name='search_by_users'),
    path('user_edit/<int:pk>/', login_required(EditFormUserView.as_view()), name='edit_user'),
    path('translations', login_required(RowsView.as_view()), name='rows'),
    path('translation_edit', translation_edit, name='translation_edit'),
    path('language_add', login_required(AddLanguageView.as_view()), name='language_add'),
    path('language_delete', language_delete, name='language_delete'),
    path('statistic', get_statistic, name='statistic'),
    path('get_statistic_90_days', get_statistic_90_days, name='get_statistic_90_days'),
    path('get_statistic_365_days', get_statistic_365_days, name='get_statistic_365_days'),
    path('arriving_audience', arriving_audience, name='arriving_audience'),
    path('arriving_audience_90_days', arriving_audience_90_days, name='arriving_audience_90_days'),
    path('arriving_audience_365_days', arriving_audience_365_days, name='arriving_audience_365_days'),
    path('login', PanelLoginView.as_view(), name='login'),
    path('get_all_broadcast_messages', get_all_broadcast_messages, name='get_all_broadcast_messages'),
    path('edit_broadcast', edit_broadcast, name='edit_broadcast'),
    path('remove_broadcast', remove_broadcast, name='remove_broadcast'),
    path('artifact_archive', artifact_archive, name='artifact_archive'),
    path('current_statistic', current_statistic, name='current_statistic'),
    path('click_statistic', click_statistic, name='click_statistic'),
    path('artifact_statistic', artifact_statistic, name='artifact_statistic'),
    path('artifact_users', artifact_users, name='artifact_users'),
    path('artifact_delete/<int:pk>/', ArtifactDeleteView.as_view(), name='artifact_delete'),
    path('artifacts_delete', artifacts_delete, name='artifacts_delete'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('state_links', login_required(StateLinkListView.as_view()), name='state_links'),
    path('create_state_link', login_required(StateLinkCreateView.as_view()), name='create_state_link'),
    path('update_state_link/<int:pk>', login_required(StateLinkUpdateView.as_view()), name='update_state_link'),
    path('remove_state_link/<int:pk>', remove_state_link, name='remove_state_link'),
]


urlpatterns += load_modules_panel_url()

panel/models.py
from django.db import models

# Create your models here.

panel/modules/scheduled_sender/views.py
from datetime import datetime
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
from django.forms import model_to_dict
from main.models import SystemLanguage, ScheduledBroadCastSendTask, STATES


@login_required
def scheduled_sender(request):
    user_id = request.GET.get('user_id', None)
    languages = SystemLanguage.objects.all()
    context = dict()
    if user_id:
        context['user_id'] = user_id
    context['date_now'] = datetime.now().strftime("%Y-%m-%dT%H:%M")
    context['languages'] = languages
    context['states'] = STATES
    return render(request, 'panel/modules/scheduled_sender/scheduled_sender.html', context)


@login_required
@csrf_exempt
def remove_scheduled_broadcast(request):
    task_id = request.POST.get('task_id')
    ScheduledBroadCastSendTask.objects.get(pk=task_id).delete()
    return HttpResponse('ok', 200)


@login_required
def get_all_scheduled_broadcast_messages(request):
    scheduled_broadcast_list = ScheduledBroadCastSendTask.objects.filter(sent=False).order_by('-send_date')
    data = {'broadcasts': []}
    for scheduled_broadcast in scheduled_broadcast_list:
        data['broadcasts'].append(
            {
                'broadcast': model_to_dict(scheduled_broadcast, exclude=['targets']),
                'date_formatted': scheduled_broadcast.date_formatted,
                'target_count': scheduled_broadcast.targets_count,
                'is_caption': not scheduled_broadcast.file_to_send_id,
            }
        )
    return JsonResponse(data)

panel/modules/site_translations/views.py
import json
from django.http import HttpResponse
from django_scaffold.settings import BASE_DIR
from django.shortcuts import render, redirect


def site_strings(request):
    with open(BASE_DIR + '/panel/modules/site_translations/ENG.json') as json_file:
        data = json.load(json_file)
        return render(request, 'panel/modules/site_translations/site_localization.html', {'data': data})


def site_translation_edit(request):
    context = {}
    key = request.GET.get('key', None)
    if key:
        with open(BASE_DIR + '/panel/modules/site_translations/ENG.json') as json_file:
            data = json.load(json_file)
        context['key'] = key
        context['text'] = data.get(key)
    else:
        return HttpResponse('Key does not exist', status=404)
    if request.method == 'POST':
        new_text = request.POST.get('text', None)
        data[key] = new_text
        with open(BASE_DIR + '/panel/modules/site_translations/ENG.json', 'w') as json_file:
            json.dump(data, json_file)
        return redirect('panel:site_rows')

    return render(request, 'panel/modules/site_translations/site_translation_edit.html', context)

panel/modules/user_to_excel/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
import pytz
from django.http import HttpResponse
from main.models import User
from panel.modules.user_to_excel.excel_utils import ExcelUserStats


@login_required()
def download_poll_pack_stats(request):
    user_list = User.objects.exclude(is_superuser=True)
    excel_poll = ExcelUserStats(user_list)
    excel_poll.user_list_sheet("Список пользователей")
    tz = pytz.timezone("Europe/Kiev")
    now = datetime.now(tz).strftime("%d_%m_%y")
    file_name = f"users_{now}.xlsx"
    stream = excel_poll.save_stream()
    response = HttpResponse(content=stream,
                            content_type='application/ms-excel')
    response['Content-Disposition'] = f'attachment; filename={file_name}'
    return response

panel/views.py
import re
from datetime import datetime, timedelta

import pygal
from django.contrib.auth.decorators import login_required
from telebot.types import InlineKeyboardButton, InlineKeyboardMarkup

from main.bot.translation_validation import MyHTMLParser
from main.models import User, StateLink, STATES, ScheduledBroadCastSendTask, ScheduledBroadCastInlineButton
from django.forms import model_to_dict
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView

from django.db.models import Q

from django_scaffold.settings import BOT_TOKEN, STORAGE_CHAT
from main.logger_settings import logger
from main.models import TokenLanguageString, LanguageString, SystemLanguage, Click, Artifact, StatisticUser, \
    BroadCastSendTask, ScheduledBroadCastSendTask, Project
from main.translations import add_new_language_default
from panel.forms import EditUserForm, AddLanguageForm, StateLinkForm, ProjectForm

from django_scaffold.settings import INSTALLED_MODULES
if INSTALLED_MODULES.get('user_history'):
    from main.modules.user_history.sender_client import SenderClient, SenderException
    from main.models import Message, File
else:
    from main.bot.sender_client import SenderClient, SenderException

SENDER_BOT = SenderClient(BOT_TOKEN)

class ShowProject(ListView):
    template_name = 'panel/project_list.html'
    paginate_by = 50
    context_object_name = 'projects'
    model = Project

    def get_queryset(self):
        print(Project.objects.all())
        return Project.objects.all()


class ProjectFormView(CreateView):
    template_name = 'panel/create.html'
    form_class = ProjectForm
    model = Project

    def get_success_url(self):
        return reverse('panel:project_list')


@login_required
def sender(request):
    user_id = request.GET.get('user_id', None)
    languages = SystemLanguage.objects.all()
    context = dict()
    if user_id:
        context['user_id'] = user_id
    context['languages'] = languages
    context['states'] = STATES
    return render(request, 'panel/sender.html', context)


@csrf_exempt
@login_required
def broadcast(request):
    message = request.POST.get('message', None)
    file_to_send = request.FILES.get('file_to_send', None)
    inline_buttons = request.POST.get('inline_buttons')
    send_date = request.POST.get('send_date', None)
    user_list_for_scheduling = []
    if not inline_buttons:
        inline_buttons = []
    else:
        inline_buttons = eval(inline_buttons)
    defined_targets = request.POST.get('defined_targets', None)
    targets = []
    send_by_language = []
    if not message and not file_to_send:
        return HttpResponse('Невозможно отправить пустое сообщение без файла', status=501)
    html_parser = MyHTMLParser()
    correct_html, error_msg = html_parser.feed(message)
    if not correct_html:
        return HttpResponse('Ошибка в тексте сообщения связаная с html: {}'.format(error_msg), status=501)
    if not defined_targets:
        for language in SystemLanguage.objects.iterator():
            if request.POST.get(language.language_code, None) == 'yes':
                send_by_language.append(language)
        if send_by_language:
            for language in send_by_language:
                for user in User.objects.filter(language=language).exclude(user_id_int=None).exclude(is_blocked=True):
                    if user.user_id_int not in targets:
                        targets.append(user.user_id_int)
                        if send_date:
                            user_list_for_scheduling.append(user)
        else:
            for user in User.objects.exclude(is_blocked=True):
                if user.user_id_s:
                    targets.append(user.user_id_s)
                    if send_date:
                        user_list_for_scheduling.append(user)
    else:
        for user_id_str in filter(None, map(str.strip, re.split('[,\s]', defined_targets))):
            if user_id_str.isdigit():
                if User.objects.filter(user_id_s=user_id_str).count():
                    if User.objects.filter(user_id_s=user_id_str).get().is_blocked != True:
                        targets.append(int(user_id_str))
                    if send_date:
                        user_list_for_scheduling.append(User.objects.get(user_id_s=user_id_str))
                else:
                    logger.error('User with id {} not found (/sendemmesage processor)'.format(user_id_str))
                    return HttpResponse('Пользователь с id {} не найден'.format(user_id_str), status=501)
            else:
                logger.error('Incorrect user id {} (/sendemmesage processor)'.format(user_id_str))
                return HttpResponse('Неправильный id пользователя {}'.format(user_id_str), status=501)

    scheduler_broadcast = None
    if send_date:
        scheduler_broadcast = ScheduledBroadCastSendTask.objects.create(message=message,
                                                                        send_date=send_date)
        scheduler_broadcast.targets.add(*user_list_for_scheduling)

    keyboard = None
    if inline_buttons:
        max_width = max([thing['pos'] for thing in inline_buttons])
        keyboard = InlineKeyboardMarkup(row_width=max_width)
        row_index = 0
        buttons_list = []
        for each in inline_buttons:
            if each['row'] > row_index:
                keyboard.add(*buttons_list)
                buttons_list = []
                row_index = each['row']
            if each['is_state'] == 'True':
                inline_button = InlineKeyboardButton(each['text'], callback_data=f'to_state;{each["state"]}')
            else:
                inline_button = InlineKeyboardButton(each['text'], url=each['url'])
            buttons_list.append(inline_button)
            if scheduler_broadcast:
                ScheduledBroadCastInlineButton.objects.create(scheduled_task=scheduler_broadcast,
                                                              text=each['text'],
                                                              url=each['url'],
                                                              state=each['state'],
                                                              to_state_enabled=each['is_state'],
                                                              row=each['row'],
                                                              column=each['pos'])
        # add last row
        if len(buttons_list):
            keyboard.add(*buttons_list)

    if len(targets):
        if file_to_send is not None:
            bot = SENDER_BOT.get_bot()
            if file_to_send.content_type.find('audio/') != -1:
                message_media = bot.send_audio(STORAGE_CHAT, file_to_send.file, title=str(file_to_send))
                if scheduler_broadcast:
                    scheduler_broadcast.file_type = 'audio'
                    scheduler_broadcast.file_to_send_id = message_media.audio.file_id
                    scheduler_broadcast.save(update_fields=['file_type', 'file_to_send_id'])
                    return HttpResponse('!', status=200)

                response = SENDER_BOT.send_audio(
                    targets,
                    message_media.audio.file_id,
                    message,
                    priority=0,
                    broadcast=True,
                    reply_markup=keyboard
                )
            elif file_to_send.content_type.find('image/') != -1:
                message_media = bot.send_photo(STORAGE_CHAT, file_to_send.file)
                if scheduler_broadcast:
                    scheduler_broadcast.file_type = 'image'
                    scheduler_broadcast.file_to_send_id = message_media.photo[-1].file_id
                    scheduler_broadcast.save(update_fields=['file_type', 'file_to_send_id'])
                    return HttpResponse('!', status=200)

                response = SENDER_BOT.send_photo(
                    targets,
                    message_media.photo[-1].file_id,
                    message,
                    priority=0,
                    broadcast=True,
                    reply_markup=keyboard
                )
            elif file_to_send.content_type.find('video/') != -1:
                message_media = bot.send_video(STORAGE_CHAT, file_to_send.file)
                if scheduler_broadcast:
                    scheduler_broadcast.file_type = 'video'
                    scheduler_broadcast.file_to_send_id = message_media.video.file_id
                    scheduler_broadcast.save(update_fields=['file_type', 'file_to_send_id'])
                    return HttpResponse('!', status=200)

                response = SENDER_BOT.send_video(
                    targets,
                    message_media.video.file_id,
                    message,
                    priority=0,
                    broadcast=True,
                    reply_markup=keyboard
                )
            else:
                message_media = bot.send_document(STORAGE_CHAT, file_to_send.file)
                if scheduler_broadcast:
                    scheduler_broadcast.file_type = 'document'
                    scheduler_broadcast.file_to_send_id = message_media.document.file_id
                    scheduler_broadcast.save(update_fields=['file_type', 'file_to_send_id'])
                    return HttpResponse('!', status=200)

                response = SENDER_BOT.send_document(
                    targets,
                    message_media.document.file_id,
                    message,
                    priority=0,
                    broadcast=True,
                    reply_markup=keyboard
                )
        else:
            if scheduler_broadcast:

panel/templates/panel/artifacts.html
{% extends "panel/admin_base.html" %}
{% block title %}Артефакты{% endblock %}
{% load static %}
{% block afterhead %}
    <link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="container align-items-center align-self-center">
        <br>
        <nav class="nav nav-pills nav-justified">
            <a class="nav-link" href="{% url 'panel:statistic' %}">График</a>
            <a class="nav-link" href="{% url 'panel:current_statistic' %}">Текущая статистика</a>
            <a class="nav-link" href="{% url 'panel:click_statistic' %}">Статистика нажатий</a>
            <a class="nav-link active" href="{% url 'panel:artifact_statistic' %}">Артефакты</a>
        </nav>

        <div class="tab-content">
            <br>
            <ul class="list-group">
                {% for art in artifacts %}
                    {% if art.is_view %}
                        <li class="list-group-item">{{ art.name }}: {{ art.count }} <a style="float: right;" class="btn btn-sm btn-danger" href="{% url 'panel:artifact_delete' art.pk %}">Удалить</a> {% if art.users_exists %}<a style="float: right;" class="btn btn-sm btn-primary" href="{% url 'panel:artifact_users' %}?key={{ art.pk }}">Просмотреть пользователей</a>{% endif %}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <br>
            <a class="btn btn-block btn-danger" href="{% url 'panel:artifacts_delete' %}">Удалить все</a>
            <br>
            <br>
            <br>
        </div>
    </div>
{% endblock %}

panel/templates/panel/click_statistic.html
{% extends "panel/admin_base.html" %}
{% block title %}Статистика кликов{% endblock %}
{% load static %}
{% block afterhead %}
<link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
<div class="container align-items-center align-self-center">
    <br>
    <nav class="nav nav-pills nav-justified">
        <a class="nav-link" href="{% url 'panel:statistic' %}">График</a>
        <a class="nav-link" href="{% url 'panel:arriving_audience' %}">Приплыв аудитории</a>
        <a class="nav-link" href="{% url 'panel:current_statistic' %}">Текущая статистика</a>
        <a class="nav-link active" href="{% url 'panel:click_statistic' %}">Статистика нажатий</a>
        <a class="nav-link" href="{% url 'panel:artifact_statistic' %}">Артефакты</a>
    </nav>

    <div class="tab-content">
        <br>
        <ul class="list-group">
            {% for click in clicks %}
            <li class="list-group-item">{{ click.name_button }}: {{ click.count }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

panel/templates/panel/language_add.html
{% extends "panel/admin_base.html" %}
{% block title %}Редактирование языков{% endblock %}
{% load static %}
{% block afterhead %}
    <link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <br>
        <form action="" method="post" class="form-horizontal col-sm-12 col-md-6 col-lg-4 shadow">
            {% csrf_token %}
            <div class="form-group">
                <p>Введите код нового языка ("ru", "ua" ... )</p>
            </div>
            {{ form }}
            <br>
            <button type="submit" class="btn btn-primary shadow_head">Сохранить</button>
            <a class="btn btn-primary shadow_head bottom-left" href="{% url 'panel:rows' %}">Отмена</a>
        </form>
    </div>
{% endblock %}

panel/templates/panel/localization.html
{% extends "panel/admin_base.html" %}
{% load get_item %}
{% load static %}
{% block afterhead %}
    <link rel="stylesheet prefetch" type="text/css" href="/static/datatables.css">
    <link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block title %}Строки{% endblock %}

{% block content %}
  <div class="container-fluid shadow table-scroll" style="width: 97%;">
      <table class="table table-bordered" id="table_users" style="width:100%">
        <thead>
          <tr>
            <th class="w-5 text-center" style="vertical-align: middle"><a href="{% url 'panel:language_add' %}"> <img src="{% static 'admin/img/icon-addlink.svg' %}" title="Добавить язык"></a></th>
            <th class="w-5 text-center" style="vertical-align: middle">Ключ</th>
            {% for code in codes %}
            <th class="w-25 text-center" style="vertical-align: middle"><a href="" onclick="if (confirm('Вы действительно хотите удалить язык?'))href='{% url 'panel:language_delete' %}?key={{code.language_code }}'"><img src="{% static 'admin/img/icon-deletelink.svg' %}" title="Удалить"></a>  {{code.language_code }}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for token, value in tokens.items %}
          <tr class="m-0">
            <td class="w-5 text-center"><a href="{% url 'panel:translation_edit' %}?key={{ token }}"><img src="{% static 'admin/img/icon-changelink.svg' %}" title="Редактировать"></a></td>
            <td class="w-5">{{ token }}</td>
            {% for val in tokens|get_item:token %}
            <td class="w-25">{{ val }}</td>
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
{% endblock %}
<script>
    alert('{{ message }}');
</script>

panel/templates/panel/project_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>List Project</title
    </head>
    <body>
        <ul>
            {% for project in projects %}
            <li>{{ project.date_hosting }}</li>
            <li>{{ project.date_domain }}</li>
            <hr/>
            {% empty %}
            <li>No object</li>
            {% endfor %}
        </ul>
    </body>
</html>

panel/templates/panel/state_links.html
{% extends "panel/admin_base.html" %}
{% load static %}
{% block title %}Настройка ссылок{% endblock %}

{% block content %}
    <div class="container-fluid">
        <br>
        <div class="container-fluid">
            <h3>Список ссылок <a href="{% url 'panel:create_state_link' %}">Добавить</a></h3>
            <div class="table-scroll">

                <table class="table table-striped table-bordered" id="table_users" style="width:100%">
                    <thead>
                    <tr>
                        <th>Ссылка</th>
                        <th>Стейт</th>
                        <th>Тег</th>
                        <th>Количество переходов</th>
                        <th>...</th>
                    </tr>
                    </thead>
                    <tbody id="table-data">
                    {% for state_link in state_links %}
                        <tr>
                            <td><a href="{{ state_link.link_id }}">{{ state_link.link_id }}</a></td>
                            <td>{{ state_link.state_name }}</td>
                            <td>{{ state_link.tag }}</td>
                            <td>{{ state_link.statistic_count }}</td>
                            <td><a href="{% url 'panel:update_state_link' state_link.pk %}">Редактировать</a> <a href="{% url 'panel:remove_state_link' state_link.pk %}">Удалить</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row" style="padding-left: 30%;">
            {% include 'panel/components/pagination.html' %}
        </div>

    </div>
{% endblock %}

panel/templates/panel/statistics_90_days.html
{% extends "panel/admin_base.html" %}
{% block title %}Статистика{% endblock %}
{% load static %}
{% block afterhead %}
<link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
<div class="container align-items-center align-self-center">
    <br>
    <nav class="nav nav-pills nav-justified">
        <a class="nav-link active" href="{% url 'panel:statistic' %}">График</a>
        <a class="nav-link" href="{% url 'panel:arriving_audience' %}">Приплыв аудитории</a>
        <a class="nav-link" href="{% url 'panel:current_statistic' %}">Текущая статистика</a>
        <a class="nav-link" href="{% url 'panel:click_statistic' %}">Статистика нажатий</a>
        <a class="nav-link" href="{% url 'panel:artifact_statistic' %}">Артефакты</a>
    </nav><br>
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link" id="nav-home-tab" href="{% url 'panel:statistic' %}" role="tab" aria-controls="nav-home" aria-selected="true">За 30 дней</a>
            <a class="nav-item nav-link active" id="nav-profile-tab"  href="{% url 'panel:get_statistic_90_days' %}" role="tab" aria-controls="nav-profile" aria-selected="false">За 3 месяца</a>
            <a class="nav-item nav-link" id="nav-contact-tab" href="{% url 'panel:get_statistic_365_days' %}" role="tab" aria-controls="nav-contact" aria-selected="false">За год</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <embed type="image/svg+xml" src={{graph_users_by_30_days|safe}} style='max-width:100%'/>
        </div>
        <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <embed type="image/svg+xml" src={{graph_users_by_90_days|safe}} style='max-width:100%'/>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <embed type="image/svg+xml" src={{graph_users_by_365_days|safe}} style='max-width:100%'/>
        </div>
    </div>
</div>
{% endblock %}

panel/templates/panel/statistics_max.html
{% extends "panel/admin_base.html" %}
{% block title %}Статистика{% endblock %}
{% load static %}
{% block afterhead %}
<link rel='stylesheet' href="{% static 'css/style.css' %}">
{% endblock %}
{% block content %}
<div class="container align-items-center align-self-center">
    <br>
    <nav class="nav nav-pills nav-justified">
        <a class="nav-link active" href="{% url 'panel:statistic' %}">График</a>
        <a class="nav-link" href="{% url 'panel:arriving_audience' %}">Приплыв аудитории</a>
        <a class="nav-link" href="{% url 'panel:current_statistic' %}">Текущая статистика</a>
        <a class="nav-link" href="{% url 'panel:click_statistic' %}">Статистика нажатий</a>
        <a class="nav-link" href="{% url 'panel:artifact_statistic' %}">Артефакты</a>
    </nav><br>
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link" id="nav-home-tab" href="{% url 'panel:statistic' %}" role="tab" aria-controls="nav-home" aria-selected="true">За 30 дней</a>
            <a class="nav-item nav-link" id="nav-profile-tab"  href="{% url 'panel:get_statistic_90_days' %}" role="tab" aria-controls="nav-profile" aria-selected="false">За 3 месяца</a>
            <a class="nav-item nav-link" id="nav-contact-tab" href="{% url 'panel:get_statistic_365_days' %}" role="tab" aria-controls="nav-contact" aria-selected="false">За год</a>
            <a class="nav-item nav-link active" id="nav-max-tab" href="{% url 'panel:get_statistic_max' %}" role="tab" aria-controls="nav-max" aria-selected="false">За все время</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <embed type="image/svg+xml" src={{graph_users_by_30_days|safe}} style='max-width:100%'/>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <embed type="image/svg+xml" src={{graph_users_by_90_days|safe}} style='max-width:100%'/>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <embed type="image/svg+xml" src={{graph_users_by_365_days|safe}} style='max-width:100%'/>
        </div>
        <div class="tab-pane fade show active" id="nav-max" role="tabpanel" aria-labelledby="nav-contact-tab">
            <embed type="image/svg+xml" src={{graph_users_max|safe}} style='max-width:100%'/>
        </div>
    </div>
</div>
{% endblock %}